wutsi:
  application:
    asset-url: https://prod-wutsi.s3.amazonaws.com/static/wutsi-web
  platform:
    security:
      api-key: "${API_KEY}"
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
