wutsi:
  application:
    asset-url: https://prod-wutsi.s3.amazonaws.com/static/wutsi-web
  platform:
    security:
      api-key: "${API_KEY}"
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/prod-wutsi"
        endpoint-url: "https://ik.imagekit.io/toifevuwjn"
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}
