wutsi:
  application:
    asset-url: https://prod-wutsi.s3.amazonaws.com/static/wutsi-assets
    server-url: https://www.wutsi.me
  platform:
    cache:
      type: memcached
      memcached:
        username: ${MEMCACHIER_USERNAME}
        password: ${MEMCACHIER_PASSWORD}
        servers: ${MEMCACHIER_SERVERS}
        ttl: 86400
    security:
      api-key: "${API_KEY}"
    image:
      type: image-kit
      image-kit:
        origin-url: "https://s3.amazonaws.com/prod-wutsi"
        endpoint-url: "https://ik.imagekit.io/toifevuwjn"
    stream:
      type: none
    storage:
      type: aws
      aws:
        bucket: prod-wutsi
